"""Replace pro_supported with esm_pro_supported and break_bug_pro_supported.
Revision ID: 0aa283fddc29
Revises: 20260322_01
Create Date: 2026-04-13 17:23:20.174684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0aa283fddc29'
down_revision: Union[str, None] = '20260322_01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'versions',
        sa.Column('esm_pro_supported', sa.JSON(), nullable=False),
    )
    op.add_column(
        'versions',
        sa.Column('break_bug_pro_supported', sa.JSON(), nullable=False),
    )
    op.add_column(
        'versions',
        sa.Column(
            'is_hidden',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.drop_column('versions', 'pro_supported')
    op.drop_constraint(
        "ck_deployments_artifact_type", "deployments", type_="check"
    )
    op.create_check_constraint(
        "ck_deployments_artifact_type",
        "deployments",
        "artifact_type IN ('snap', 'deb', 'charm', 'image', 'rock')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'versions',
        sa.Column(
            'pro_supported',
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column('versions', 'is_hidden')
    op.drop_column('versions', 'break_bug_pro_supported')
    op.drop_column('versions', 'esm_pro_supported')
    op.drop_constraint(
        "ck_deployments_artifact_type", "deployments", type_="check"
    )
    op.create_check_constraint(
        "ck_deployments_artifact_type",
        "deployments",
        "artifact_type IN ('snap', 'deb', 'charm', 'image', 'rock', 'other')",
    )
    # ### end Alembic commands ###
